easy_admin:
    site_name: 'Madatsara'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        Event:
            class: App\Entity\Event
        AccessType:
            class: App\Entity\AccessType
        Api:
            class: App\Entity\Api
        Status:
            class: App\Entity\Status
        Subscriber:
            class: App\Entity\Subscriber
        Thematic:
            class: App\Entity\Thematic
        Artiste:
            class: App\Entity\Artiste
        MemberEvent:
            class: App\Entity\MemberEvent
        Organisateur:
            class: App\Entity\Organisateur
        Place:
            class: App\Entity\Place
        Commune:
            class: App\Entity\Commune
        Quartier:
            class: App\Entity\Quartier
        Region:
            class: App\Entity\Region
