easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        - App\Entity\Event
        - App\Entity\AccessType
        - App\Entity\Api
        - App\Entity\Status
        - App\Entity\Subscriber
        - App\Entity\Thematic
        - App\Entity\Artiste
        - App\Entity\MemberEvent
        - App\Entity\Organisateur
        - App\Entity\Place
        - App\Entity\Commune
        - App\Entity\Quartier
        - App\Entity\Region
