easy_admin:
    site_name: 'Madatsara'
    design:
        brand_color: '#9b2c2c'

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        AccessType:
            class: App\Entity\AccessType
        Api:
            class: App\Entity\Api
        Artiste:
            class: App\Entity\Artiste
        Commune:
            class: App\Entity\Commune
        Event:
            class: App\Entity\Event
        MemberEvent:
            class: App\Entity\MemberEvent
        Organisateur:
            class: App\Entity\Organisateur
        Place:
            class: App\Entity\Place
        Quartier:
            class: App\Entity\Quartier
        Region:
            class: App\Entity\Region
        Status:
            class: App\Entity\Status
        Subscriber:
            class: App\Entity\Subscriber
        Thematic:
            class: App\Entity\Thematic
