#index:
#    path: /
#    controller: App\Controller\DefaultController::index
acme_privacy:
  path: /privacy.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'frontend/static/privacy.html.twig'
    site_name: 'Madatsara'

free:
    path: /free_fr.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: http://free.fr
      permanent: true

contact_page:
  path: /oldcontact.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: frontend_contact
    permanent: true

app_customloader:
    resource: .
    type: customloader
