name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: mrabs/schoolmg-app-mg:exif

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: madatsara
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: composer update
        run: composer update --prefer-dist --no-ansi --no-interaction --no-progress

  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH_DEVELOP }}
            git pull
            dep deploy